# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-QXiz7xfs6n9Zf8hLmtCCiKrhDPBfYLS
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

# Example small dataset
data = np.array([23, 45, 67, 12, 89, 34, 56])

# Number of bootstrap samples
n_bootstraps = 1000

# Bootstrap resampling
bootstrap_means = np.zeros(n_bootstraps)
for i in range(n_bootstraps):
    sample = np.random.choice(data, size=len(data), replace=True)
    bootstrap_means[i] = np.mean(sample)

# Bootstrap confidence interval (e.g., 95%)
bootstrap_ci = np.percentile(bootstrap_means, [2.5, 97.5])

# Analytical confidence interval (using t-distribution for small sample)
n = len(data)
mean = np.mean(data)
std_error = stats.sem(data)
analytical_ci = stats.t.interval(confidence=0.95, df=n-1, loc=mean, scale=std_error)

# Plotting the bootstrap distribution
plt.figure(figsize=(10, 6))
plt.hist(bootstrap_means, bins=30, color='#1f77b4', edgecolor='black', alpha=0.7)
plt.axvline(x=bootstrap_ci[0], color='r', linestyle='--', label=f'Bootstrap CI: [{bootstrap_ci[0]:.2f}, {bootstrap_ci[1]:.2f}]')
plt.axvline(x=bootstrap_ci[1], color='r', linestyle='--')
plt.axvline(x=analytical_ci[0], color='g', linestyle='-', label=f'Analytical CI: [{analytical_ci[0]:.2f}, {analytical_ci[1]:.2f}]')
plt.axvline(x=analytical_ci[1], color='g', linestyle='-')
plt.axvline(x=mean, color='k', linestyle='-', label=f'Mean: {mean:.2f}')
plt.title('Bootstrap Distribution of the Mean')
plt.xlabel('Mean Value')
plt.ylabel('Frequency')
plt.legend()
plt.show()

# Print results
print(f"Bootstrap CI: [{bootstrap_ci[0]:.2f}, {bootstrap_ci[1]:.2f}]")
print(f"Analytical CI: [{analytical_ci[0]:.2f}, {analytical_ci[1]:.2f}]")